### ISSUE TITLE
두가지 룰의 상호 간섭으로 인한 고민 공유

### ISSUE THREAD

**Issue by vreality64** [naver/eslint-config-naver#10]
안녕하세요. FE 플랫폼 박성현입니다.  
`eslint-config-naver` 룰 사용 중 고민이 되는 컨벤션이 있어서 질문차 이슈 올립니다.

### 상황
아래 ES5 코드를 ES6 로 전환하려 했습니다.
```js
days.map(function (day) {
  return (day < 10) ? "0"+day : ""+day;
});
```
<br>

코드는 숫자 배열(1 ~ 31)을, 자리수에 따라 적절하게 문자 배열(01 ~ 31)로 바꿉니다.  
날짜 포맷팅을 위해 하는 건데요. ES6 코드로는 아래처럼 변경되길 원했습니다.

```js
days.map(day => day < 10 ? `0${day}` : `${day}`);
```
그런데 이 코드는 아래 룰을 위반했기 때문에 `lint` 과정에서 에러를 뿜어냅니다.  

> `no-confusing-arrow`: arrow  함수 내에서 비교 연산자와 헷갈릴 가능성이 있을 땐, 괄호 없이 사용하지 못한다.
<br>

그래서 바꾼 코드입니다.

```js
// step 1 code, no-confusing-arrow 룰 해결
days.map(day => {
  return day < 10 ? `0${day}` : `${day}`;
});
```
하지만 이 코드는 아래 룰을 위반합니다..

> `arrow-body-style`: arrow 함수의 {} 는 필요할 때만 사용한다
<br>

결국 최종적으로 아래 코드로 변환했습니다.

```js
// step 2 code, final code
days.map(day => {
  const converted = day < 10 ? `0${day}` : `${day}`;

  return converted;
});
```

### 이슈
결국 `no-confusing-arrow` 룰과 `arrow-body-style` 룰이 상호 간섭하는 이슈인데요.  
이후 메서드 체이닝까지 생각해봤을 때, 최종 변환된 코드는 조금 ugly 하지 않나 생각이 듭니다.  

### 질문
이 이슈에 대해서 어떤 생각이 가지고 계신지 한번 의견을 나눠봤으면 합니다. 저만 불편한 건가요?

**Comment by hiuny** [comment]
아래 처럼 하면 lint 통과돼요~ 저렇게 하면 ugly하지 않을 것 같은데,, 어떤가요?

```javascript
days.map(day => (day < 10 ? `0${day}` : `${day}`));
```

**Comment by VReality64** [comment]
lint 는 통과되지만 아직도 미묘하네요... 삼항 연산자 전체를 괄호로 감싸는 경우는 별로 사용해본적이 없어서요. 삼항 연사자에 괄호를 사용한다면, 아래처럼 부분별로 사용했던 것 같아요.
```js
(day < 10) ? `0${day}` : `${day}`;

// ->
days.map(day => (day < 10) ? `0${day}` : `${day}`);
```
혹시 이 코드는 lint 에 걸릴까요?  

추가적으로 온라인에서 룰 통과 여부를 확인해볼 수 있는 방법이 없을까요? 테스트 해볼 수 있는 playground가 있으면 좋을거 같아요.

**Comment by hiuny** [comment]
화살표 함수의 body가 한 줄이면 그 표현식을 평가한 후의 값을 리턴값으로 취급을 하는 데요, 그 표현식이 삼항문인 경우 반환값이 불분명하다는 이슈가 있는 거고, 그래서 삼항문 전체를 괄호로 감싸서 삼항문 표현식이 평가된 후의 값을 리턴하겠다 라고 명시적으로 표현해주는 거라서 삼항문 전체를 감싸는 거에요. 조건부분만 감싸는 건 여전히 lint에 걸릴 듯..

**Comment by VReality64** [comment]
그렇네요. 말씀해주신대로 삼항문 전체를 괄호로 감싸는 방법만 가능하겠네요. 어떤 방법을 사용하는게 좋을지 더 생각해봐야겠네요. 감사합니다 😃

**Comment by boxersb** [comment]
이 경우에는 삼항연산자 전체를 감싸는것이 맞아보이네요..  
비슷한 예로.. arrow function 을 사용하여 객체를 바로 리턴하고자할때는 이렇게 쓸 수 밖에 없습니다.

```js
days.map( day => ({ month: m, day: d }) );
```

()를 생략하면 function body 로 인식하기 때문에 이게 자연스러운데요.. 같은 맥락에서, 삼항 연산자도 이렇게 처리하는게 어떨까요?

@weumj 님 의견 주세요~

**Comment by weumj** [comment]
이 룰을 적용하는 이유는 @hiuny 님이 말씀해주신 것 처럼, arrow-function과 삼항연산자 간 혼동의 여지가 있기 때문이라고 생각합니다.

```js
var x = a => 1 ? 2 : 3;

var x = a <= 1 ? 2 : 3;
```

https://eslint.org/docs/rules/no-confusing-arrow

**Comment by boxersb** [comment]
이런 경우에는 return 표현식을 () 로 감싸는것으로 의견이 모인것 같네요~~  
이슈 close 하겠습니다~
