### ISSUE TITLE
v1.0.1 호환성 이슈

### ISSUE THREAD

**Issue by weumj** [naver/eslint-config-naver#16]
`eslint-config-naver`를 사용하는 프로젝트의 eslint 의존성이 다음과 같이 되어있는 경우 호환성 문제가 발생합니다.

```json
{
    "eslint": "^3.x.x",
    "eslint-config-naver": "^1.0.0"
}
```
---

eslint-config-naver를 설치하면 `eslint-config-naver@1.0.1` 가 설치됩니다.
1.0.1 버전은 eslint-4.x.x 룰셋을 사용하고, 프로젝트에 설치되는 eslint-3.x.x 이기 때문에 다음 에러가 발생합니다.

![image](https://user-images.githubusercontent.com/7656085/30900602-980d1d7a-a39f-11e7-94e1-c2ebf817a9d0.png)

**Comment by VReality64** [comment]
`eslint-config-naver@2.0.0` 릴리즈로는 위 이슈를 해결할 수 없습니다.

eslint-3.x 룰셋을 사용하는 `eslint-config-naver@1.x` 버전 패치가 추가로 필요합니다.

**Comment by sculove** [comment]
@VReality64 1.0.3을 재배포 했습니다. 제보해주셔서 감사합니다.
