### ISSUE TITLE
parserOptions.ecmaFeatures.experimentalObjectRestSpread' option is deprecated

### ISSUE THREAD

**Issue by gaepury** [naver/eslint-config-naver#22]
lint 체크 시 

~~~
[ESLINT_LEGACY_OBJECT_REST_SPREAD] DeprecationWarning: The 'parserOptions.ecmaFeatures.experimentalObjectRestSpread' option is deprecated. Use 'parserOptions.ecmaVersion' instead. (found in "node_modules/eslint-config-naver/eslint-config-airbnb-base/index.js")
~~~
메세지가 뜹니다.
eslint-config-airbnb-base 변경사항에 따른 영향이라 생각되어집니다.

해당 경로 index.js에서 ecmaFetures속성 제거 부탁드립니다.

**Comment by JaeYeopHan** [comment]
@gaepury  https://github.com/naver/eslint-config-naver/pull/18/files 에서 진행되고 있습니다. 이슈 등록 고맙습니다!

**Comment by boxersb** [comment]
https://github.com/naver/eslint-config-naver/blob/master/eslint-config-airbnb-base/index.js#L15
해당 이슈 아직 재현됩니다.
`2.0.3` 버전으로 패치 예정입니다.

**Comment by boxersb** [comment]
- [v2.0.3](https://www.npmjs.com/package/eslint-config-naver/v/2.0.3) 릴리즈 완료 했습니다.
